config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#index'
  get '/tasks/new', to: 'tasks#new'
  get '/tasks/:id', to: 'tasks#show', as: :task
  post '/tasks', to: 'tasks#create'
  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch '/tasks/:id', to: 'tasks#update'
  delete '/tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :fetch_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(create_task_params)
    @task.save

    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(update_task_params)

    redirect_to @task
  end

  def destroy
    @task.destroy

    redirect_to tasks_path
  end

  private

  def create_task_params
    params.require(:task).permit(:title, :details)
  end

  def update_task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def fetch_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :details %>
    <%= f.text_field :details %>
  </div>

  <% if @task.persisted? %>
    <div>
      <%= f.label :completed %>
      <%= f.check_box :completed %>
    </div>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h2>Updating <%= @task.title %></h2>

<%= render 'form' %>

app/views/tasks/index.html.erb
<h2>List of tasks</h2>

<%= link_to 'Create new task', tasks_new_path %>

<ul></ul>
<% @tasks.each do |task| %>
  <li>
  <%= task.completed? ? "[x]" : "[ ]" %> <%= task.title %>
  <p>
    <%= link_to 'Show details', task %> - <%= link_to 'Delete', task_path(task), method: :delete %>
  </p>
  </li>
<% end %>
</ul>

app/views/tasks/new.html.erb
<h2>Add a new task</h2>

<%= render 'form' %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>

<p><%= link_to 'Edit task', edit_path(@task) %></p>

<%= link_to 'Go back', tasks_path %>